      SUBROUTINE  RCALF1(BBCALL)
C 
C        RCALF1 SETS UP THE -BBCALL- VECTOR FOR RCALF
C 
      SAVE
      INCLUDE  'RCACM'
      REAL  BBCALL(MXBC,NOSYS)

      DO 100 ISYS=1,NOSYS
       DO 100 IB=1,NOBCALL
  100   BBCALL(IB,ISYS) = 0.

      DO 200 ISYS=1,NOSYS
       DO 200 IB=1,NOBC(ISYS)
        IX = IBC(1,IB,ISYS)
        IY = IBC(2,IB,ISYS)
        IZ = IBC(3,IB,ISYS)
        DO 150 IBALL=1,NOBCALL
          IF(IX.EQ.IBCALL(1,IBALL) .AND. IY.EQ.IBCALL(2,IBALL) .AND.
     .       IZ.EQ.IBCALL(3,IBALL))  BBCALL(IBALL,ISYS) = BBC(IB,ISYS)
  150   CONTINUE
  200 CONTINUE

      RETURN
      END
