      SUBROUTINE RCASPLTS
C 
C        RCASPLTS IS THE MASTER SUBROUTINE USED FOR INTEGRATING THE
C                 DIFFERENTIAL EQUATIONS OF THE WATER QUALITY MODEL.
C                 TIME DERIVATIVE: EXPLICIT - SPLIT TIMESTEP
C                 SPACE DERIVATIVE: UPWIND WITH SMOLARKIEWICZ CORRECTOR
C
C
C************************************************************************
C 
      INCLUDE 'RCACM' 
      WRITE(OUT,1000)
 1000 FORMAT(///20X,'SORRY, RCASPLTS IS NOT A VALID OPTION FOR THE PUBLI
     .C DOMAIN VERSION OF RCA'/20X,'PROGRAM TERMINATED'//)
      CALL EXIT
      END 
