      SUBROUTINE RCASPLT
C 
C        RCASPLT IS THE MASTER SUBROUTINE USED FOR INTEGRATING THE DIFFERENTIAL
C                EQUATIONS OF THE WATER QUALITY MODEL.
C                TIME DERIVATIVE: EXPLICIT - SPLIT TIMESTEP
C                SPACE DERIVATIVE: UPWIND
C
C************************************************************************
C 
      INCLUDE 'RCACM' 
      WRITE(OUT,1000)
 1000 FORMAT(///20X,'SORRY, RCASPLT IS NOT A VALID OPTION FOR THE PUBLIC
     . DOMAIN VERSION OF RCA'/20X,'PROGRAM TERMINATED'//)
      CALL EXIT
      END 
